version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:12.18.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install --save

  image_deployment_script:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Add Linode VPS host key to known_hosts
          command: |
            ssh-keyscan -H 45.79.115.237 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
          - $NEW_SSH_CCI_LINODE
      - run:
          name: Deploy to Linode VPS
          command: |
            scp -o StrictHostKeyChecking=no ./deployWhodabase.sh root@45.79.115.237:/tmp/
            ssh -o StrictHostKeyChecking=no root@45.79.115.237 'bash /tmp/deployWhodabase.sh'

workflows:
  update_whodabase:
    jobs:
      - build_and_test
      - image_deployment_script:
          requires:
            - build_and_test
          filters:
            branches:
              only: deploy_live